services:

    bread_api.cart_service:
        class: Bread\ApiBundle\Service\CartService
        arguments:
            - "@session"

    bread_api.request_helper_service:
        class: Bread\ApiBundle\Service\RequestHelperService
        arguments:
            - "@validator"
