services:

    bread_api.cart_service:
        class: Bread\ApiBundle\Service\CartService
        arguments:
            - "@session"

    bread_api.user_service:
        class: Bread\ApiBundle\Service\UserService
        arguments:
            - "@doctrine.orm.entity_manager"

    bread_api.form_builder:
        class: Bread\ApiBundle\Form\FormBuilder

    bread_api.form_service:
        class: Bread\ApiBundle\Form\FormService
        abstract: true
        public: false
        arguments:
            - "@validator"
            - "@security.csrf.token_manager"
            - "@bread_api.form_builder"

    bread_api.feedback_type:
        class: Bread\ApiBundle\Form\FeedbackType
        parent: bread_api.form_service
        public: true
