imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BreadContentBundle/Resources/config/services.yml" }
    - { resource: "@BreadApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: ~
#        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets:
        packages:
            js: ~
            css: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'BreadContentBundle:Form:custom_fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

#Doctrine migrations
doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/Bread/ContentBundle/DoctrineMigrations"
    namespace: Bread\ContentBundle\DoctrineMigrations
    table_name: migration_versions
    name: Byngovskoe PO Migrations

#Doctrine extension
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            sortable: true
            timestampable: true

#Image crop
bread_content:
    save_dir: "%kernel.root_dir%/../web/media/images"
    asset_dir: "media/images"
    entities:
        product:
            min_width: 1500
            min_height: 1000
            max_width: 5000
            max_height: 4000
            crop_size:
                width: 1000
                height: 1000
            mime_types: ['jpeg', 'png']
        declaration:
            min_width: 1500
            min_height: 1000
            max_width: 5000
            max_height: 4000
            crop_size:
                width: 1000
                height: 600
            mime_types: ['jpeg', 'png']
        slide:
            min_width: 1500
            min_height: 1000
            max_width: 5000
            max_height: 4000
            crop_size:
                width: 1000
                height: 400
            mime_types: ['jpeg', 'png']
        news:
            min_width: 1500
            min_height: 1000
            max_width: 5000
            max_height: 4000
            crop_size:
                width: 400
                height: 400
            mime_types: ['jpeg', 'png']
            max_count: 5

#Sonata admin
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title:      CMS
    title_logo: bundles/breadcontent/images/cms_logo.png
    templates:
        layout: 'BreadContentBundle:Admin:layout.html.twig'
        edit: 'BreadContentBundle:Admin:edit.html.twig'
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
            cms.content:
                label: Контент
                icon: '<i class="fa fa-file-text"></i>'
            cms.products:
                label: Продукция
                icon: '<i class="fa fa-truck"></i>'
            cms.requests:
                label: Заявки
                icon: '<i class="fa fa-address-book"></i>'

#fos user
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Bread\ContentBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

#assetic
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    filters:
        cssrewrite: ~
    bundles:
        - SonataAdminBundle
        - BreadContentBundle
    assets:
        libsjs:
            inputs:
                - 'bundles/breadcontent/js/libs.min.js'
        commonjs:
            inputs:
                - 'bundles/breadcontent/js/jquery/common.js'
        core_module:
            inputs:
                - 'bundles/breadcontent/js/angular/core/core.module.js'
                - 'bundles/breadcontent/js/angular/core/controllers/*.js'
        appjs:
            inputs:
                - '@core_module'
                - 'bundles/breadcontent/js/angular/app.js'
