services:
    app.admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, AppBundle:Admin/ImageCrop]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.products, label: Продукция }

    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.products, label: Категории продукции }

    app.admin.flour:
        class: AppBundle\Admin\FlourAdmin
        arguments: [~, AppBundle\Entity\Flour, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.products, label: Сорта муки }

    app.admin.unit:
        class: AppBundle\Admin\UnitAdmin
        arguments: [~, AppBundle\Entity\Unit, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.products, label: Единицы измерения }

    app.admin.client:
        class: AppBundle\Admin\ClientAdmin
        arguments: [~, AppBundle\Entity\Client, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.requests, label: Список клиентов }

    app.admin.order:
        class: AppBundle\Admin\OrderAdmin
        arguments: [~, AppBundle\Entity\Order, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.requests, label: Заявки }

    app.admin.menu:
        class: AppBundle\Admin\MenuAdmin
        arguments: [~, AppBundle\Entity\Menu, 'PixSortableBehaviorBundle:SortableAdmin']
        calls:
            - [ setPositionService, ["@pix_sortable_behavior.position.orm"]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.content, label: Меню }

    app.admin.company:
        class: AppBundle\Admin\CompanyAdmin
        arguments: [~, AppBundle\Entity\Company, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.content, label: Компания }

    app.admin.declaration:
        class: AppBundle\Admin\DeclarationAdmin
        arguments: [~, AppBundle\Entity\Declaration, AppBundle:Admin/ImageCrop]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.content, label: Декларации }

    app.admin.slide:
        class: AppBundle\Admin\SlideAdmin
        arguments: [~, AppBundle\Entity\Slide, AppBundle:Admin/ImageCrop]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.content, label: Слайды }

    app.admin.news:
        class: AppBundle\Admin\NewsAdmin
        arguments: [~, AppBundle\Entity\News, AppBundle:Admin/ImageCrop]
        tags:
            - { name: sonata.admin, manager_type: orm, group: cms.content, label: Новости }